train_config:
  model_id_prefix: 'segmentation-model-small'
  dataset_id: 'dataset-small'
  segmentation_model:
    model_name: '3DUnet'
    model_parameters:
      backbone_name: 'vgg16'
      encoder_weights: Null
      input_shape: '(None, None, None, 1)'
  loss: 'cross_entropy'
  optimizer: 'adam'
  batch_size: 8
  epochs: 2
  training_data_shuffle_seed: 1234
  data_augmentation:
    random_90-degree_rotations: True
