train_config:
  model_id_prefix: 'segmentation-model-fpn-efficientnetb0-study2'
  dataset_id: 'dataset-esrf16_study2_CropCase5_TrnValCaseB'
  segmentation_model:
    model_name: 'FPN'
    model_parameters:
      backbone_name: 'efficientnetb0'
      encoder_weights: Null   # Null (random initialization) or 'imagenet' (pre-training on ImageNet, only RGB images)
      input_shape: [Null, Null, 1]
      activation: 'sigmoid'
  loss: 'cross_entropy'
  optimizer: 'adam'
  batch_size: 8    # p100
  epochs: 10
  training_data_shuffle_seed: 1234
  validation_data_shuffle_seed: 12345
  test_data_shuffle_seed: 123456
  data_augmentation:
    random_90-degree_rotations: True
