dataset_config:
  dataset_split:
    train: [
      "THIN_REF_S2_P1_L3_2496_1563_2159"
    ]
    validation: [
      "THIN_CNT_S2_P1_L4_2334_1578_2159",
    ]
    test: [
      "8bit_AS4_S2_P1_L6_2560_1750_2160",
    ]
  stack_downsampling:
    type: 'linear' # 'None', 'random', 'linear', 'from_start', 'from_end'
#    frac: 1.0
    number_of_images: 100
    num_skip_beg_slices: 0 # trims n slices off of beginning of stack with N total slices. Slice n+1 becomes new Slice 1
    num_skip_end_slices: 0 # trims m slices off of end of stack with N total slices. Slice N-(m+1) becomes new last slice
  target_size: [512, 512]
  image_cropping:
    type: 'random' # 'None', 'random'
    num_per_image: 1 # 1 is all that is supported at the moment
  class_annotation_mapping:
    class_0_annotation_GVs: [100, 175]
    class_1_annotation_GVs: [250]
