train_config:
  model_id_prefix: 'segmentation-model-small-3class_tfversion_debug'
  dataset_id: 'dataset-small-3class_tfversion_debug'
  segmentation_model:
    model_name: 'Unet'
    model_parameters:
      backbone_name: 'vgg16'
      encoder_weights: Null   # Null (random initialization) or 'imagenet' (pre-training on ImageNet)
      input_shape: [Null, Null, 1]
      activation: 'sigmoid'
  loss: 'binary_cross_entropy' #'binary_cross_entropy' 'categorical_cross_entropy' 'mean_squared_error' 'mean_absolute_error'
  optimizer: 'adam' # 'adam', 'sdg', 'adagrad', 'adamax', 'ftrl', 'nadam', 'rmsprop'
  batch_size: 16    # p100
  epochs: 10
  training_data_shuffle_seed: 1234
  validation_data_shuffle_seed: 12345
  test_data_shuffle_seed: 123456
  data_augmentation:
    random_90-degree_rotations: False
